--drop table if exists doctors cascade;
--drop table if exists patients cascade;
--drop table if exists tickets cascade;
--drop table if exists schedule cascade;
--drop table if exists time_slot cascade;

CREATE TABLE IF NOT EXISTS doctors
(
    doctor_id   bigint       NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    doctor_name varchar(256) NOT NULL,
    speciality  varchar(128) NOT NULL,
    CONSTRAINT doctors_pkey PRIMARY KEY (doctor_id)
);

CREATE TABLE IF NOT EXISTS patients
(
    patient_id    bigint       NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    patient_name  varchar(256) NOT NULL,
    date_of_birth date         NOT NULL,
    CONSTRAINT patients_pkey PRIMARY KEY (patient_id)
);

CREATE TABLE IF NOT EXISTS tickets
(
    ticket_id  bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    doctor_id  bigint NOT NULL,
    patient_id bigint,
    visit_time TIME   NOT NULL,
    CONSTRAINT tickets_pkey PRIMARY KEY (ticket_id),
    CONSTRAINT fk_tickets_doctor
        FOREIGN KEY (doctor_id)
            REFERENCES doctors (doctor_id) ON DELETE CASCADE,
    CONSTRAINT fk_tickets_patient
        FOREIGN KEY (patient_id)
            REFERENCES patients (patient_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS schedule
(
    schedule_id        bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    day_of_reception   DATE   NOT NULL,
    doctor_id          bigint NOT NULL,
    start_of_reception TIME   NOT NULL,
    end_of_reception   TIME   NOT NULL,
    CONSTRAINT schedule_pkey PRIMARY KEY (schedule_id),
    CONSTRAINT fk_schedule_doctor
        FOREIGN KEY (doctor_id)
            REFERENCES doctors (doctor_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS time_slot
(
    time_slot_id    bigint  NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    time_slot_start TIME    NOT NULL,
    available       boolean NOT NULL,
    schedule_id     bigint,
    CONSTRAINT slot_pkey PRIMARY KEY (time_slot_id)
);